-- Custom admin users. Generate password_hash with bcrypt; never store plaintext passwords.
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(trim(full_name)) > 0),
  username text not null unique check (char_length(trim(username)) >= 3),
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.admin_users enable row level security;
revoke all on public.admin_users from anon, authenticated;

-- Create the first user through the server-side admin API after setting SUPABASE_SERVICE_ROLE_KEY.
-- Example hash generation: node -e "console.log(require('bcryptjs').hashSync('ChangeMe123!', 12))"
-- insert into public.admin_users (full_name, username, password_hash) values ('Administrator', 'admin', '<bcrypt-hash>');
