-- Awards displayed on the clinic website.
create table if not exists public.awards (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  description text not null check (char_length(trim(description)) > 0),
  image_urls text[] not null default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.awards add column if not exists image_urls text[] not null default '{}';

create or replace function public.set_awards_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists awards_updated_at on public.awards;
create trigger awards_updated_at
before update on public.awards
for each row execute procedure public.set_awards_updated_at();

alter table public.awards enable row level security;
drop policy if exists "Anon can read awards" on public.awards;
drop policy if exists "Anon can insert awards" on public.awards;
drop policy if exists "Anon can update awards" on public.awards;
drop policy if exists "Anon can delete awards" on public.awards;
create policy "Anon can read awards" on public.awards for select to anon using (true);
create policy "Anon can insert awards" on public.awards for insert to anon with check (true);
create policy "Anon can update awards" on public.awards for update to anon using (true) with check (true);
create policy "Anon can delete awards" on public.awards for delete to anon using (true);

insert into storage.buckets (id, name, public)
values ('award-images', 'award-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anon can upload award images" on storage.objects;
drop policy if exists "Public can view award images" on storage.objects;
drop policy if exists "Anon can delete award images" on storage.objects;
create policy "Anon can upload award images" on storage.objects for insert to anon with check (bucket_id = 'award-images');
create policy "Public can view award images" on storage.objects for select to public using (bucket_id = 'award-images');
create policy "Anon can delete award images" on storage.objects for delete to anon using (bucket_id = 'award-images');
