-- Blog posts displayed on the clinic website.
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  short_description text not null check (char_length(trim(short_description)) > 0),
  content text not null check (char_length(trim(content)) > 0),
  author text not null check (char_length(trim(author)) > 0),
  category text not null check (char_length(trim(category)) > 0),
  image_url text,
  published_date date,
  status text not null default 'Draft' check (status in ('Draft', 'Published')),
  is_featured boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.blog_posts add column if not exists image_url text;
alter table public.blog_posts add column if not exists published_date date;
alter table public.blog_posts add column if not exists status text not null default 'Draft';
alter table public.blog_posts add column if not exists is_featured boolean not null default false;

create or replace function public.set_blog_posts_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists blog_posts_updated_at on public.blog_posts;
create trigger blog_posts_updated_at
before update on public.blog_posts
for each row execute procedure public.set_blog_posts_updated_at();

alter table public.blog_posts enable row level security;
drop policy if exists "Anon can read blog posts" on public.blog_posts;
drop policy if exists "Anon can insert blog posts" on public.blog_posts;
drop policy if exists "Anon can update blog posts" on public.blog_posts;
drop policy if exists "Anon can delete blog posts" on public.blog_posts;
create policy "Anon can read blog posts" on public.blog_posts for select to anon using (true);
create policy "Anon can insert blog posts" on public.blog_posts for insert to anon with check (true);
create policy "Anon can update blog posts" on public.blog_posts for update to anon using (true) with check (true);
create policy "Anon can delete blog posts" on public.blog_posts for delete to anon using (true);

insert into storage.buckets (id, name, public) values ('blog-images', 'blog-images', true) on conflict (id) do update set public = true;
drop policy if exists "Anon can upload blog images" on storage.objects;
drop policy if exists "Public can view blog images" on storage.objects;
drop policy if exists "Anon can delete blog images" on storage.objects;
create policy "Anon can upload blog images" on storage.objects for insert to anon with check (bucket_id = 'blog-images');
create policy "Public can view blog images" on storage.objects for select to public using (bucket_id = 'blog-images');
create policy "Anon can delete blog images" on storage.objects for delete to anon using (bucket_id = 'blog-images');
