-- Clinic information used by the admin portal.
create table if not exists public.clinic_information (
  id bigint generated by default as identity primary key,
  clinic_title text not null check (char_length(trim(clinic_title)) > 0),
  about_us text,
  address text,
  profile_image_url text,
  emergency_phone text not null check (char_length(trim(emergency_phone)) > 0),
  phone text not null check (char_length(trim(phone)) > 0),
  email text not null check (email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_clinic_information_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists clinic_information_updated_at on public.clinic_information;
create trigger clinic_information_updated_at
before update on public.clinic_information
for each row execute procedure public.set_clinic_information_updated_at();

alter table public.clinic_information enable row level security;

alter table public.clinic_information add column if not exists address text;
alter table public.clinic_information add column if not exists profile_image_url text;

insert into storage.buckets (id, name, public)
values ('clinic-images', 'clinic-images', true)
on conflict (id) do update set public = true;

-- The current frontend uses the anon key and has no login flow yet.
drop policy if exists "Anon can read clinic information" on public.clinic_information;
drop policy if exists "Anon can insert clinic information" on public.clinic_information;
drop policy if exists "Anon can update clinic information" on public.clinic_information;
drop policy if exists "Anon can delete clinic information" on public.clinic_information;
create policy "Anon can read clinic information"
on public.clinic_information for select to anon using (true);
create policy "Anon can insert clinic information"
on public.clinic_information for insert to anon with check (true);
create policy "Anon can update clinic information"
on public.clinic_information for update to anon using (true) with check (true);
create policy "Anon can delete clinic information"
on public.clinic_information for delete to anon using (true);

drop policy if exists "Anon can upload clinic images" on storage.objects;
drop policy if exists "Public can view clinic images" on storage.objects;
drop policy if exists "Anon can delete clinic images" on storage.objects;
create policy "Anon can upload clinic images"
on storage.objects for insert to anon with check (bucket_id = 'clinic-images');
create policy "Public can view clinic images"
on storage.objects for select to public using (bucket_id = 'clinic-images');
create policy "Anon can delete clinic images"
on storage.objects for delete to anon using (bucket_id = 'clinic-images');

-- For production, replace the anon policies with authenticated policies after adding login.
