-- Corporate information displayed on the clinic website.
create table if not exists public.corporate (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  description text not null check (char_length(trim(description)) > 0),
  image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.corporate add column if not exists image_url text;

create or replace function public.set_corporate_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists corporate_updated_at on public.corporate;
create trigger corporate_updated_at
before update on public.corporate
for each row execute procedure public.set_corporate_updated_at();

alter table public.corporate enable row level security;
drop policy if exists "Anon can read corporate" on public.corporate;
drop policy if exists "Anon can insert corporate" on public.corporate;
drop policy if exists "Anon can update corporate" on public.corporate;
drop policy if exists "Anon can delete corporate" on public.corporate;
create policy "Anon can read corporate" on public.corporate for select to anon using (true);
create policy "Anon can insert corporate" on public.corporate for insert to anon with check (true);
create policy "Anon can update corporate" on public.corporate for update to anon using (true) with check (true);
create policy "Anon can delete corporate" on public.corporate for delete to anon using (true);

insert into storage.buckets (id, name, public) values ('corporate-images', 'corporate-images', true) on conflict (id) do update set public = true;
drop policy if exists "Anon can upload corporate images" on storage.objects;
drop policy if exists "Public can view corporate images" on storage.objects;
drop policy if exists "Anon can delete corporate images" on storage.objects;
create policy "Anon can upload corporate images" on storage.objects for insert to anon with check (bucket_id = 'corporate-images');
create policy "Public can view corporate images" on storage.objects for select to public using (bucket_id = 'corporate-images');
create policy "Anon can delete corporate images" on storage.objects for delete to anon using (bucket_id = 'corporate-images');
