-- Doctors displayed on the clinic website.
create table if not exists public.doctors (
  id bigint generated by default as identity primary key,
  doctor_name text not null check (char_length(trim(doctor_name)) > 0),
  facility text not null check (char_length(trim(facility)) > 0),
  address text not null check (char_length(trim(address)) > 0),
  phone text not null check (char_length(trim(phone)) > 0),
  gender text not null check (gender in ('Female', 'Male', 'Other')),
  qualifications text not null check (char_length(trim(qualifications)) > 0),
  biography text not null check (char_length(trim(biography)) > 0),
  image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.doctors add column if not exists image_url text;
alter table public.doctors add column if not exists facility text not null default 'Main Clinic';

create or replace function public.set_doctors_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists doctors_updated_at on public.doctors;
create trigger doctors_updated_at
before update on public.doctors
for each row execute procedure public.set_doctors_updated_at();

alter table public.doctors enable row level security;
drop policy if exists "Anon can read doctors" on public.doctors;
drop policy if exists "Anon can insert doctors" on public.doctors;
drop policy if exists "Anon can update doctors" on public.doctors;
drop policy if exists "Anon can delete doctors" on public.doctors;
create policy "Anon can read doctors" on public.doctors for select to anon using (true);
create policy "Anon can insert doctors" on public.doctors for insert to anon with check (true);
create policy "Anon can update doctors" on public.doctors for update to anon using (true) with check (true);
create policy "Anon can delete doctors" on public.doctors for delete to anon using (true);

insert into storage.buckets (id, name, public)
values ('doctor-images', 'doctor-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anon can upload doctor images" on storage.objects;
drop policy if exists "Public can view doctor images" on storage.objects;
drop policy if exists "Anon can delete doctor images" on storage.objects;
create policy "Anon can upload doctor images" on storage.objects for insert to anon with check (bucket_id = 'doctor-images');
create policy "Public can view doctor images" on storage.objects for select to public using (bucket_id = 'doctor-images');
create policy "Anon can delete doctor images" on storage.objects for delete to anon using (bucket_id = 'doctor-images');
