-- Management team members displayed on the clinic website.
create table if not exists public.management_team (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  position text not null check (char_length(trim(position)) > 0),
  department text not null check (char_length(trim(department)) > 0),
  description text not null check (char_length(trim(description)) > 0),
  image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.management_team add column if not exists image_url text;

create or replace function public.set_management_team_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists management_team_updated_at on public.management_team;
create trigger management_team_updated_at
before update on public.management_team
for each row execute procedure public.set_management_team_updated_at();

alter table public.management_team enable row level security;
drop policy if exists "Anon can read management team" on public.management_team;
drop policy if exists "Anon can insert management team" on public.management_team;
drop policy if exists "Anon can update management team" on public.management_team;
drop policy if exists "Anon can delete management team" on public.management_team;
create policy "Anon can read management team" on public.management_team for select to anon using (true);
create policy "Anon can insert management team" on public.management_team for insert to anon with check (true);
create policy "Anon can update management team" on public.management_team for update to anon using (true) with check (true);
create policy "Anon can delete management team" on public.management_team for delete to anon using (true);

insert into storage.buckets (id, name, public)
values ('team-images', 'team-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anon can upload team images" on storage.objects;
drop policy if exists "Public can view team images" on storage.objects;
drop policy if exists "Anon can delete team images" on storage.objects;
create policy "Anon can upload team images" on storage.objects for insert to anon with check (bucket_id = 'team-images');
create policy "Public can view team images" on storage.objects for select to public using (bucket_id = 'team-images');
create policy "Anon can delete team images" on storage.objects for delete to anon using (bucket_id = 'team-images');
