-- Medical packages displayed on the clinic website.
create table if not exists public.medical_packages (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  short_description text not null check (char_length(trim(short_description)) > 0),
  description text not null check (char_length(trim(description)) > 0),
  price numeric(10,2) not null check (price >= 0),
  duration text not null check (char_length(trim(duration)) > 0),
  included_services text not null check (char_length(trim(included_services)) > 0),
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.medical_packages enable row level security;
drop policy if exists "Anon can read medical packages" on public.medical_packages;
drop policy if exists "Anon can insert medical packages" on public.medical_packages;
drop policy if exists "Anon can update medical packages" on public.medical_packages;
drop policy if exists "Anon can delete medical packages" on public.medical_packages;
create policy "Anon can read medical packages" on public.medical_packages for select to anon using (true);
create policy "Anon can insert medical packages" on public.medical_packages for insert to anon with check (true);
create policy "Anon can update medical packages" on public.medical_packages for update to anon using (true) with check (true);
create policy "Anon can delete medical packages" on public.medical_packages for delete to anon using (true);

insert into storage.buckets (id, name, public) values ('package-images', 'package-images', true) on conflict (id) do update set public = true;
drop policy if exists "Anon can upload package images" on storage.objects;
drop policy if exists "Public can view package images" on storage.objects;
drop policy if exists "Anon can delete package images" on storage.objects;
create policy "Anon can upload package images" on storage.objects for insert to anon with check (bucket_id = 'package-images');
create policy "Public can view package images" on storage.objects for select to public using (bucket_id = 'package-images');
create policy "Anon can delete package images" on storage.objects for delete to anon using (bucket_id = 'package-images');
