-- Mission, vision, and core values content for the admin portal.
create table if not exists public.mission_vision_core (
  id bigint generated by default as identity primary key,
  section_type text not null check (section_type in ('Mission', 'Vision', 'Core Value')),
  title text not null check (char_length(trim(title)) > 0),
  description text not null check (char_length(trim(description)) > 0),
  image_url text,
  display_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_mission_vision_core_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists mission_vision_core_updated_at on public.mission_vision_core;
create trigger mission_vision_core_updated_at
before update on public.mission_vision_core
for each row execute procedure public.set_mission_vision_core_updated_at();

alter table public.mission_vision_core enable row level security;
alter table public.mission_vision_core add column if not exists image_url text;

insert into storage.buckets (id, name, public)
values ('mission-images', 'mission-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anon can read mission vision core" on public.mission_vision_core;
drop policy if exists "Anon can insert mission vision core" on public.mission_vision_core;
drop policy if exists "Anon can update mission vision core" on public.mission_vision_core;
drop policy if exists "Anon can delete mission vision core" on public.mission_vision_core;
create policy "Anon can read mission vision core" on public.mission_vision_core for select to anon using (true);
create policy "Anon can insert mission vision core" on public.mission_vision_core for insert to anon with check (true);
create policy "Anon can update mission vision core" on public.mission_vision_core for update to anon using (true) with check (true);
create policy "Anon can delete mission vision core" on public.mission_vision_core for delete to anon using (true);

drop policy if exists "Anon can upload mission images" on storage.objects;
drop policy if exists "Public can view mission images" on storage.objects;
drop policy if exists "Anon can delete mission images" on storage.objects;
create policy "Anon can upload mission images" on storage.objects for insert to anon with check (bucket_id = 'mission-images');
create policy "Public can view mission images" on storage.objects for select to public using (bucket_id = 'mission-images');
create policy "Anon can delete mission images" on storage.objects for delete to anon using (bucket_id = 'mission-images');
