-- Promotions displayed on the clinic website.
create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  description text not null check (char_length(trim(description)) > 0),
  discount_type text not null check (discount_type in ('Percentage', 'Fixed amount')),
  discount_value numeric(10,2) not null check (discount_value >= 0),
  start_date date not null,
  end_date date not null check (end_date >= start_date),
  promo_code text,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.promotions enable row level security;
drop policy if exists "Anon can read promotions" on public.promotions;
drop policy if exists "Anon can insert promotions" on public.promotions;
drop policy if exists "Anon can update promotions" on public.promotions;
drop policy if exists "Anon can delete promotions" on public.promotions;
create policy "Anon can read promotions" on public.promotions for select to anon using (true);
create policy "Anon can insert promotions" on public.promotions for insert to anon with check (true);
create policy "Anon can update promotions" on public.promotions for update to anon using (true) with check (true);
create policy "Anon can delete promotions" on public.promotions for delete to anon using (true);

insert into storage.buckets (id, name, public) values ('promotion-images', 'promotion-images', true) on conflict (id) do update set public = true;
drop policy if exists "Anon can upload promotion images" on storage.objects;
drop policy if exists "Public can view promotion images" on storage.objects;
drop policy if exists "Anon can delete promotion images" on storage.objects;
create policy "Anon can upload promotion images" on storage.objects for insert to anon with check (bucket_id = 'promotion-images');
create policy "Public can view promotion images" on storage.objects for select to public using (bucket_id = 'promotion-images');
create policy "Anon can delete promotion images" on storage.objects for delete to anon using (bucket_id = 'promotion-images');
