-- Services displayed on the clinic website.
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  description text not null check (char_length(trim(description)) > 0),
  image_urls text[] not null default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.services add column if not exists image_urls text[] not null default '{}';

create or replace function public.set_services_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists services_updated_at on public.services;
create trigger services_updated_at
before update on public.services
for each row execute procedure public.set_services_updated_at();

alter table public.services enable row level security;
drop policy if exists "Anon can read services" on public.services;
drop policy if exists "Anon can insert services" on public.services;
drop policy if exists "Anon can update services" on public.services;
drop policy if exists "Anon can delete services" on public.services;
create policy "Anon can read services" on public.services for select to anon using (true);
create policy "Anon can insert services" on public.services for insert to anon with check (true);
create policy "Anon can update services" on public.services for update to anon using (true) with check (true);
create policy "Anon can delete services" on public.services for delete to anon using (true);

insert into storage.buckets (id, name, public)
values ('service-images', 'service-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anon can upload service images" on storage.objects;
drop policy if exists "Public can view service images" on storage.objects;
drop policy if exists "Anon can delete service images" on storage.objects;
create policy "Anon can upload service images" on storage.objects for insert to anon with check (bucket_id = 'service-images');
create policy "Public can view service images" on storage.objects for select to public using (bucket_id = 'service-images');
create policy "Anon can delete service images" on storage.objects for delete to anon using (bucket_id = 'service-images');
